// SLParseTable.swift
// Defines the Binary Subtree Representation (BSR) elements and builds the
// SL parse table  𝒯_Γ^SL  used by simpleET() in Section 7.1.
//
// A BSR element  (Ω, i, k, j)  represents a binarised derivation subtree:
//   Ω  is either a complete production or a left-prefix of a rhs
//   i  is the left extent   (start input position)
//   k  is the pivot         (split point)
//   j  is the right extent  (end input position)
//
// SL table entry  𝒯_Γ^SL(p, x) = (m, A_{p,x}, χ₁, χ₂)  where
//   m         = next NFA state (or ⊥)
//   A_{p,x}   = completer set (SLR(1) lookahead)
//   χ₁        = m(G_p, x)   BSR components for direct transitions
//   χ₂        = em(G_p, x)  BSR components for nullable contributions
//
// Grammar library API:
//   production.goal : NonTerminal
//   production.rule : [Symbol]
//   grammar.followSets() -> [NonTerminal: Set<Symbol>]
//   grammar.isNullable(_ nt: NonTerminal) -> Bool

import Foundation
import Grammar
import Parser

// MARK: - BSR Grammar Component (Ω)
//
// Formerly a separate `BSRComponent` enum with `.production(Production)` /
// `.prefix(lhs:symbols:)` cases, each independently reduced to a `NodeLabel`
// by the (goal, symbols, position) triple at every consumption site. Both
// cases now construct that `NodeLabel` directly instead — see `mSets`/`eSets`
// below — the same unification `EarleyParser` (the chart-based sibling
// package) applies to its own `.pnode`/`.snode` split. `NodeLabel.isCompleted`
// (`position == symbols.count`) is what distinguished `.production` from
// `.prefix`.
//
// `BSRElement(omega:leftExtent:pivot:rightExtent:)` is likewise now just the
// shared `BSR<NodeLabel>(label:leftExtent:pivot:rightExtent:)`.

// MARK: - m(M, x) — direct BSR components

/// m(M, x): BSR components generated by a direct transition on symbol x ≠ ε.
///
/// For each slot  Y ::= α · x β  in M:
///   • If β is empty (x is the last symbol):  emit NodeLabel(Y ::= αx, complete)
///   • Otherwise (prefix αx has length ≥ 1):  emit NodeLabel(Y ::= αx·β, partial)
///
/// m(M, ε) = ∅
///
/// (Scott & Johnstone 2026, Section 6.4)
func mSets(_ M: Set<Slot>, symbol x: Symbol) -> Set<NodeLabel> {
    guard !isEpsilonSymbol(x) else { return [] }

    var result = Set<NodeLabel>()
    for slot in M {
        guard let next = slot.nextSymbol, next == x else { continue }
        // The dot moves one step past x, i.e. to slot.dot + 1 — regardless of
        // whether that lands on the end of the rule (complete) or partway
        // through it (partial); `NodeLabel.isCompleted` tells them apart.
        result.insert(NodeLabel(goal: slot.production.goal, symbols: slot.production.rule, position: slot.dot + 1))
    }
    return result
}

// MARK: - em(M) — nullable BSR components

/// e(M): the set of BSR components arising from nullable symbols after the dot.
///
/// For each slot  Y ::= α · ω β  in M  where ω ⟹* ε:
///   • If α is non-empty:  emit NodeLabel(Y ::= α·ωβ, partial) — the dot stays at α's end
///   • If α is empty:      emit NodeLabel(Y ::= ω…, complete) — the whole nullable suffix collapses
///
/// Used to compute χ₂ = em(move(G_p, x)) for the SL table.
///
/// (Scott & Johnstone 2026, Section 6.5)
func eSets(_ M: Set<Slot>, grammar: Grammar) -> Set<NodeLabel> {
    var result = Set<NodeLabel>()
    for slot in M {
        var position = slot.dot
        while position < slot.production.rule.count {
            let nullable: Bool
            switch slot.production.rule[position] {
            case .nonTerminal(let nt): nullable = grammar.isNullable(nt)
            case .terminal(let terminal): nullable = terminal.isEmpty
            case .metaSymbol: nullable = false
            }
            guard nullable else { break }
            position += 1
            result.insert(NodeLabel(
                goal: slot.production.goal,
                symbols: slot.production.rule,
                position: position))
        }
    }
    return result
}

// MARK: - Static nullable-prefix labels (closure-time absorption)
//
// BUG FIX (see EarleyParser.swift's simpleET() for the full rationale):
//
// `lnCallSlots(for:)` can add a slot `X ::= α · ω β` (dot > 0) to a state's
// closure purely because the *prefix* α is nullable — no NFA transition is
// ever crossed to reach that dot position; it is baked into the state the
// moment X is "called" via `calls()`. This happens whenever a production has
// two or more *consecutive* nullable symbols (e.g. Γ₂'s `S ::= B B S a`,
// where both `B`s can be absorbed with zero input consumed) or is a literal
// `X ::= ε` production.
//
// Both `mSets` and `eSets` only ever run on states that are the *target* of
// an actual NFA transition (`nfa.transition(from:on:)`). A state that is
// itself the *initial* state (or, more generally, any state whose relevant
// slots arrived purely via `calls()` and were never the destination of a
// move on a real symbol) is therefore never fed to either function — so the
// `NodeLabel`s for those in-between dot positions are simply never created,
// and `buildSPPF` finds nothing when it later looks them up. The result is a
// dead-end `.intermediate`/`.symbol` node that `SPPFGraph.cleanup()` quietly
// prunes — taking its ancestor chain, and sometimes the whole parse tree,
// with it. This is the root cause of "SPPF only partially constructed" for
// any grammar with adjacent nullable symbols.
//
// The fix: precompute, for every NFA state, the full set of `NodeLabel`s
// implied by *just being in that state* — independent of any transition —
// and seed them into Υ eagerly whenever the traversal (`simpleET`/`parseET`)
// discovers the state is reachable at some input position j. Since these
// labels always describe a zero-width span (nothing was consumed to reach
// them), the seeded BSR element is always `(label, j, j, j)`.

/// For an NFA state (a set of grammar slots), the `NodeLabel`s describing
/// every nullable-prefix dot position that `calls()` folded into the state
/// without crossing a transition — for every nonterminal the state calls.
///
/// Includes both:
///   • partial slots (`dot >= 1`, prefix nullable but the production isn't
///     fully done) — e.g. `S ::= B·BSa`, `S ::= BB·Sa`
///   • the trivially-complete case (`dot == 0 == rule.count`, i.e. a literal
///     `X ::= ε` production) — these need the exact same eager treatment for
///     the exact same reason: no transition ever visits them either.
///
/// `dot == 0` slots where `rule` is non-empty are excluded: they carry no
/// information beyond "X was called here", which the entailment closure
/// already captures structurally.
func staticNullableLabels(in state: Set<Slot>, grammar: Grammar) -> Set<NodeLabel> {
    var result = Set<NodeLabel>()
    let called = Set(state.filter { $0.dot == 0 }.map { $0.production.goal })
    for nt in called {
        for slot in grammar.lnCallSlots(for: nt) where slot.dot >= 1 || slot.isComplete {
            result.insert(NodeLabel(
                goal: slot.production.goal,
                symbols: slot.production.rule,
                position: slot.dot))
        }
    }
    return result
}

// MARK: - SL Parse Table Entry

public struct SLTableEntry {
    /// Next NFA state index (nil = ⊥).
    public let nextState:    Int?
    /// Completer set A_{p,x}: nonterminals Y with Y ::= γ· ∈ G_p and x ∈ FOLLOW(Y).
    public let completedNTs: Set<NonTerminal>
    /// χ₁ = m(G_p, x): BSR components for the direct transition on x.
    public let chi1:         Set<NodeLabel>
    /// χ₂ = em(move(G_p,x)): BSR components for nullable contributions.
    public let chi2:         Set<NodeLabel>
}

// MARK: - SL Parse Table

public struct SLParseTable {
    /// entries[state][symbolKey] = SLTableEntry
    let entries: [[String: SLTableEntry]]
    public let nfa: EarleyNFA
    public let grammar: Grammar

    /// See `RecogniserTable.patternTerminals`'s doc comment — same purpose,
    /// same reason it's needed, computed once here from `grammar` rather than
    /// threaded in separately.
    let patternTerminals: [(terminal: Terminal, key: String)]

    /// staticNullables[state] — see `staticNullableLabels(in:grammar:)` above.
    /// Indexed by NFA state; seeded eagerly by `simpleET`/`parseET` whenever a
    /// state is discovered reachable at some input position.
    let staticNullables: [Set<NodeLabel>]

    public init(entries: [[String: SLTableEntry]], nfa: EarleyNFA, grammar: Grammar) {
        self.entries = entries
        self.nfa = nfa
        self.grammar = grammar
        self.patternTerminals = collectPatternTerminals(for: grammar)
        self.staticNullables = nfa.states.map { staticNullableLabels(in: $0, grammar: grammar) }
    }

    public func entry(state p: Int, symbol x: String) -> SLTableEntry? {
        guard p < entries.count else { return nil }
        return entries[p][x]
    }

    /// The static nullable-prefix labels implied by state `p` alone — see
    /// `staticNullableLabels(in:grammar:)`.
    func staticNullableEntries(state p: Int) -> Set<NodeLabel> {
        guard p < staticNullables.count else { return [] }
        return staticNullables[p]
    }

    /// See `RecogniserTable.resolveKey(forToken:)`'s doc comment — identical
    /// purpose: bridges a raw input token's literal text to the key its
    /// matching table column (which may be a regex/range/list pattern's own
    /// text, not the token's) is actually stored under.
    public func resolveKey(forToken token: String) -> String {
        for (terminal, key) in patternTerminals where terminal.matches(.string(string: token)) {
            return key
        }
        return token
    }
}

// MARK: - Table Builder

public func buildSLParseTable(nfa: EarleyNFA, grammar: Grammar) -> SLParseTable {
    let follow = grammar.followSets()   // [NonTerminal: Set<Symbol>]
    let epsilonSym: Symbol = .terminal(.meta(.eps))

    var entries = [[String: SLTableEntry]](repeating: [:], count: nfa.stateCount)

    for p in 0..<nfa.stateCount {
        let gp = nfa.states[p]

        // ── Terminal columns (+ end-of-input "$") ──
        let terminalSymbols: [Symbol] = grammar.terminals.map { .terminal($0) }
            + [.terminal(.meta(.eof))]

        for sym in terminalSymbols {
            let key = symbolKey(sym)
            let next = nfa.transition(from: p, on: sym)

            // Completer set A_{p,x}: complete slots whose FOLLOW contains sym.
            var completed = Set<NonTerminal>()
            for slot in gp where slot.isComplete {
                let y = slot.production.goal
                if follow[y]?.contains(sym) == true {
                    completed.insert(y)
                }
            }

            let chi1 = mSets(gp, symbol: sym)
            let chi2: Set<NodeLabel> = next.map { h in eSets(nfa.states[h], grammar: grammar) } ?? []

            entries[p][key] = SLTableEntry(
                nextState: next, completedNTs: completed, chi1: chi1, chi2: chi2)
        }

        // ── Nonterminal columns ──
        for nt in grammar.nonTerminals {
            let sym = Symbol.nonTerminal(nt)
            let key = symbolKey(sym)
            let next = nfa.transition(from: p, on: sym)

            let chi1 = mSets(gp, symbol: sym)
            let chi2: Set<NodeLabel> = next.map { h in eSets(nfa.states[h], grammar: grammar) } ?? []

            entries[p][key] = SLTableEntry(
                nextState: next, completedNTs: [], chi1: chi1, chi2: chi2)
        }

        // ── ε column ──
        let epsNext = nfa.transition(from: p, on: epsilonSym)
        entries[p][epsilonKey] = SLTableEntry(
            nextState: epsNext, completedNTs: [], chi1: [], chi2: [])
    }

    return SLParseTable(entries: entries, nfa: nfa, grammar: grammar)
}
