// ParseTable.swift
// Defines the Binary Subtree Representation (BSR) elements and builds the
// SL parse table  𝒯_Γ^SL  used by simpleET() in Section 7.1.
//
// A BSR element  (Ω, i, k, j)  represents a binarised derivation subtree:
//   Ω  is either a complete production or a left-prefix of a rhs
//   i  is the left extent   (start input position)
//   k  is the pivot         (split point)
//   j  is the right extent  (end input position)
//
// SL table entry  𝒯_Γ^SL(p, x) = (m, A_{p,x}, χ₁, χ₂)  where
//   m         = next NFA state (or ⊥)
//   A_{p,x}   = completer set (SLR(1) lookahead)
//   χ₁        = m(G_p, x)   BSR components for direct transitions
//   χ₂        = em(G_p, x)  BSR components for nullable contributions
//
// Grammar library API:
//   production.goal : NonTerminal
//   production.rule : [Symbol]
//   grammar.followSets() -> [NonTerminal: Set<Symbol>]
//   grammar.isNullable(_ nt: NonTerminal) -> Bool

import Foundation
import Grammar

// MARK: - BSR Grammar Component (Ω)

/// The grammar component of a BSR element — either a full production or
/// a left-prefix string of length ≥ 1 (used for intermediate binarisation).
public enum BSRComponent: Hashable, CustomStringConvertible {
    /// A complete production  X ::= γ.
    case production(Production)
    /// A left-prefix  δ  of some production rhs.
    /// `lhs` is the production head; `symbols` is the prefix [α₀…αₖ].
    case prefix(lhs: NonTerminal, symbols: [Symbol])

    public var description: String {
        switch self {
        case .production(let p):
            let rhs = p.rule.isEmpty ? "ε" : p.rule.map(\.description).joined(separator: " ")
            return "\(p.goal.name) ::= \(rhs)"
        case .prefix(let lhs, let syms):
            return "\(lhs.name) ::= \(syms.map(\.description).joined(separator: " "))"
        }
    }

    /// The LHS nonterminal of this component.
    public var lhsNonterminal: NonTerminal? {
        switch self {
        case .production(let p): return p.goal
        case .prefix(let lhs, _): return lhs
        }
    }
}

// MARK: - BSR Element

/// A BSR element  (Ω, i, k, j).
public struct BSRElement: Hashable, CustomStringConvertible {
    public let omega:       BSRComponent
    public let leftExtent:  Int   // i
    public let pivot:       Int   // k
    public let rightExtent: Int   // j

    public var description: String {
        "(\(omega), \(leftExtent), \(pivot), \(rightExtent))"
    }
}

// MARK: - m(M, x) — direct BSR components

/// m(M, x): BSR components generated by a direct transition on symbol x ≠ ε.
///
/// For each slot  Y ::= α · x β  in M:
///   • If β is empty (x is the last symbol):  emit .production(Y ::= αx)
///   • Otherwise (prefix αx has length ≥ 1):  emit .prefix(Y, αx)
///
/// m(M, ε) = ∅
///
/// (Scott & Johnstone 2026, Section 6.4)
func mSets(_ M: Set<Slot>, symbol x: Symbol) -> Set<BSRComponent> {
    guard !isEpsilonSymbol(x) else { return [] }

    var result = Set<BSRComponent>()
    for slot in M {
        guard let next = slot.nextSymbol, next == x else { continue }
        // newRhs = rule[0 ..< dot+1]  (everything up to and including x)
        let newRhs = Array(slot.production.rule[...(slot.dot)])

        if slot.dot + 1 == slot.production.rule.count {
            // x was the last symbol — this is a complete production prefix
            result.insert(.production(slot.production))
        } else {
            // x is a non-final symbol — emit prefix component
            result.insert(.prefix(lhs: slot.production.goal, symbols: newRhs))
        }
    }
    return result
}

// MARK: - em(M) — nullable BSR components

/// e(M): the set of BSR components arising from nullable symbols after the dot.
///
/// For each slot  Y ::= α · ω β  in M  where ω ⟹* ε:
///   • If α is non-empty:  emit .prefix(Y, α)
///   • If α is empty:      emit .production(Y ::= ω …)
///
/// Used to compute χ₂ = em(move(G_p, x)) for the SL table.
///
/// (Scott & Johnstone 2026, Section 6.5)
func eSets(_ M: Set<Slot>, grammar: Grammar) -> Set<BSRComponent> {
    var result = Set<BSRComponent>()
    for slot in M {
        guard let next = slot.nextSymbol else { continue }
        let nextIsNullable: Bool
        switch next {
        case .nonTerminal(let nt): nextIsNullable = grammar.isNullable(nt)
        case .terminal(let t):     nextIsNullable = t.isEmpty
        case .metaSymbol:          nextIsNullable = false
        }
        guard nextIsNullable else { continue }

        let prefix = Array(slot.production.rule[..<slot.dot])
        if prefix.isEmpty {
            result.insert(.production(slot.production))
        } else {
            result.insert(.prefix(lhs: slot.production.goal, symbols: prefix))
        }
    }
    return result
}

// MARK: - SL Parse Table Entry

public struct SLTableEntry {
    /// Next NFA state index (nil = ⊥).
    public let nextState:    Int?
    /// Completer set A_{p,x}: nonterminals Y with Y ::= γ· ∈ G_p and x ∈ FOLLOW(Y).
    public let completedNTs: Set<NonTerminal>
    /// χ₁ = m(G_p, x): BSR components for the direct transition on x.
    public let chi1:         Set<BSRComponent>
    /// χ₂ = em(move(G_p,x)): BSR components for nullable contributions.
    public let chi2:         Set<BSRComponent>
}

// MARK: - SL Parse Table

public struct SLParseTable {
    /// entries[state][symbolKey] = SLTableEntry
    let entries: [[String: SLTableEntry]]
    public let nfa: EarleyNFA
    public let grammar: Grammar

    /// See `RecogniserTable.patternTerminals`'s doc comment — same purpose,
    /// same reason it's needed, computed once here from `grammar` rather than
    /// threaded in separately.
    let patternTerminals: [(terminal: Terminal, key: String)]

    public init(entries: [[String: SLTableEntry]], nfa: EarleyNFA, grammar: Grammar) {
        self.entries = entries
        self.nfa = nfa
        self.grammar = grammar
        self.patternTerminals = collectPatternTerminals(for: grammar)
    }

    public func entry(state p: Int, symbol x: String) -> SLTableEntry? {
        guard p < entries.count else { return nil }
        return entries[p][x]
    }

    /// See `RecogniserTable.resolveKey(forToken:)`'s doc comment — identical
    /// purpose: bridges a raw input token's literal text to the key its
    /// matching table column (which may be a regex/range/list pattern's own
    /// text, not the token's) is actually stored under.
    public func resolveKey(forToken token: String) -> String {
        for (terminal, key) in patternTerminals where terminal.matches(.string(token)) {
            return key
        }
        return token
    }
}

// MARK: - Table Builder

public func buildSLParseTable(nfa: EarleyNFA, grammar: Grammar) -> SLParseTable {
    let follow = grammar.followSets()   // [NonTerminal: Set<Symbol>]
    let epsilonSym: Symbol = .terminal(.meta(.eps))

    var entries = [[String: SLTableEntry]](repeating: [:], count: nfa.stateCount)

    for p in 0..<nfa.stateCount {
        let gp = nfa.states[p]

        // ── Terminal columns (+ end-of-input "$") ──
        let terminalSymbols: [Symbol] = grammar.terminals.map { .terminal($0) }
            + [.terminal(.meta(.eof))]

        for sym in terminalSymbols {
            let key = symbolKey(sym)
            let next = nfa.transition(from: p, on: sym)

            // Completer set A_{p,x}: complete slots whose FOLLOW contains sym.
            var completed = Set<NonTerminal>()
            for slot in gp where slot.isComplete {
                let y = slot.production.goal
                if follow[y]?.contains(sym) == true {
                    completed.insert(y)
                }
            }

            let chi1 = mSets(gp, symbol: sym)
            let chi2: Set<BSRComponent> = next.map { h in eSets(nfa.states[h], grammar: grammar) } ?? []

            entries[p][key] = SLTableEntry(
                nextState: next, completedNTs: completed, chi1: chi1, chi2: chi2)
        }

        // ── Nonterminal columns ──
        for nt in grammar.nonTerminals {
            let sym = Symbol.nonTerminal(nt)
            let key = symbolKey(sym)
            let next = nfa.transition(from: p, on: sym)

            let chi1 = mSets(gp, symbol: sym)
            let chi2: Set<BSRComponent> = next.map { h in eSets(nfa.states[h], grammar: grammar) } ?? []

            entries[p][key] = SLTableEntry(
                nextState: next, completedNTs: [], chi1: chi1, chi2: chi2)
        }

        // ── ε column ──
        let epsNext = nfa.transition(from: p, on: epsilonSym)
        entries[p][epsilonKey] = SLTableEntry(
            nextState: epsNext, completedNTs: [], chi1: [], chi2: [])
    }

    return SLParseTable(entries: entries, nfa: nfa, grammar: grammar)
}
